# Generated by Django 5.2.15 on 2026-09-10 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.JSONField(default=dict)),
                ('frequency', models.CharField(max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=10)),
                ('next_run_at', models.DateTimeField(db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('last_issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.issue')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurrence.schedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'scheduled_at'), name='birdplane_occurrence_once')],
            },
        ),
    ]
